import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from 'react-hot-toast';
import GoogleAnalytics from "@/components/GoogleAnalytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nuzrat Carpet Emporium",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
                <script
                    async
                    src={`https://www.googletagmanager.com/gtag/js?id=YOUR_GA_TRACKING_ID`}
                ></script>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            window.dataLayer = window.dataLayer || [];
                            function gtag(){dataLayer.push(arguments);}
                            gtag('js', new Date());
                            gtag('config', 'YOUR_GA_TRACKING_ID', {
                                page_path: window.location.pathname,
                            });
                        `,
                    }}
                ></script>
            </head>
      <body className={inter.className}>
      <GoogleAnalytics trackingId="YOUR_GA_TRACKING_ID" />
          {children}
          <Toaster />
      </body>
    </html>
  );
}

