import { Inter } from "next/font/google";
import "../globals.css";
import SideMenu from "@/components/Sidemenu";
import NavbarDashboard from "@/components/NavbarDashboard";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nuzrat Carpet Emporium",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} data-cjcrx="addYes">
      <div className={`grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[250px_1fr]`}>
        <SideMenu/>
        <div className="flex flex-col">
          <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
            <NavbarDashboard/>
            {children}
            
          </main>
        </div>
        <ToastContainer position="top-right" autoClose={3000} theme="light" />
      </div>
    </body>
    </html>
  );
}